[package]
name = "twiddler"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"
mylzo = "0.1.1"
zerocopy = "0.7.35"
zerocopy-derive = "0.7.35"
